name: eleaguehub
description: EleagueHub MVP skeleton (Android only)
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter

  # State + DI
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.7

  # Persistence
  shared_preferences: ^2.2.3

  # Nice to have
  intl: ^0.19.0

dev_dependencies:
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
