
  # Nice to have
  intl: ^0.19.0

dev_dependencies:
  mobile_scanner: ^5.1.0
  qr_flutter: ^4.1.0
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
